.PHONY: clean All

All:
	@echo "----------Building project:[ ROMAppConsoleTest - Debug ]----------"
	@cd "ROMAppConsoleTest" && $(MAKE) -f  "ROMAppConsoleTest.mk"
clean:
	@echo "----------Cleaning project:[ ROMAppConsoleTest - Debug ]----------"
	@cd "ROMAppConsoleTest" && $(MAKE) -f  "ROMAppConsoleTest.mk" clean
